Fix syntax for overriding rule severity
If you invoke `ast-grep scan --error foo`, then `foo` will be
interpreted as a filename:

```bash
$ ast-grep scan --error unused-suppression
ERROR: unused-suppression: No such file or directory (os error 2)
```

Make the docs match `ast-grep scan --help` output, which requires
setting `--(error|warning|info|hint)` using `=`.

I think this was comprehensive
==============================
`git grep -E '\-\-(error|warning|info|hint|off) '` returns no entries.